# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\20190822\Admin_Resigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1286, 761)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/cat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 70, 531, 661))
        self.tabWidget.setStyleSheet("\n"
"\n"
"QTabBar::tab {\n"
"        border-top:0px solid rgb(45, 45, 45);\n"
"        border-top-left-radius: 4px;\n"
"        border-top-right-radius: 4px;\n"
"        color: rgb(175, 175, 175);\n"
"        height: 329px;\n"
"        min-width: 85px;\n"
"        margin-right: 5px;\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lin_bumen_id = QtWidgets.QLineEdit(self.tab)
        self.lin_bumen_id.setGeometry(QtCore.QRect(230, 330, 161, 41))
        self.lin_bumen_id.setObjectName("lin_bumen_id")
        self.lin_bumen_name = QtWidgets.QLineEdit(self.tab)
        self.lin_bumen_name.setGeometry(QtCore.QRect(20, 330, 161, 41))
        self.lin_bumen_name.setObjectName("lin_bumen_name")
        self.lin_email = QtWidgets.QLineEdit(self.tab)
        self.lin_email.setGeometry(QtCore.QRect(20, 420, 161, 41))
        self.lin_email.setObjectName("lin_email")
        self.lin_card_id = QtWidgets.QLineEdit(self.tab)
        self.lin_card_id.setGeometry(QtCore.QRect(20, 240, 161, 41))
        self.lin_card_id.setObjectName("lin_card_id")
        self.lin_worker_name = QtWidgets.QLineEdit(self.tab)
        self.lin_worker_name.setGeometry(QtCore.QRect(230, 160, 161, 41))
        self.lin_worker_name.setObjectName("lin_worker_name")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(80, 290, 51, 16))
        self.label.setObjectName("label")
        self.com_desc = QtWidgets.QComboBox(self.tab)
        self.com_desc.setGeometry(QtCore.QRect(160, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.com_desc.setFont(font)
        self.com_desc.setObjectName("com_desc")
        self.com_desc.addItem("")
        self.com_desc.addItem("")
        self.com_desc.addItem("")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(90, 200, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(80, 470, 31, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(170, 530, 71, 51))
        self.pushButton.setObjectName("pushButton")
        self.lin_phone = QtWidgets.QLineEdit(self.tab)
        self.lin_phone.setGeometry(QtCore.QRect(230, 240, 161, 41))
        self.lin_phone.setObjectName("lin_phone")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(280, 380, 61, 21))
        self.label_10.setObjectName("label_10")
        self.lin_worker_id = QtWidgets.QLineEdit(self.tab)
        self.lin_worker_id.setGeometry(QtCore.QRect(20, 160, 161, 41))
        self.lin_worker_id.setObjectName("lin_worker_id")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(280, 290, 61, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 90, 51, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(70, 380, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(290, 210, 31, 16))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 80, 311, 461))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.lab_lh_address = QtWidgets.QLabel(self.centralwidget)
        self.lab_lh_address.setGeometry(QtCore.QRect(930, 20, 51, 31))
        self.lab_lh_address.setStyleSheet("")
        self.lab_lh_address.setObjectName("lab_lh_address")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 20, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tab_thing_all = QtWidgets.QTableWidget(self.centralwidget)
        self.tab_thing_all.setEnabled(True)
        self.tab_thing_all.setGeometry(QtCore.QRect(570, 70, 701, 661))
        self.tab_thing_all.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab_thing_all.setObjectName("tab_thing_all")
        self.tab_thing_all.setColumnCount(8)
        self.tab_thing_all.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_thing_all.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_thing_all.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_thing_all.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_thing_all.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_thing_all.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_thing_all.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_thing_all.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_thing_all.setHorizontalHeaderItem(7, item)
        self.but_return_bind_wire = QtWidgets.QPushButton(self.centralwidget)
        self.but_return_bind_wire.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.but_return_bind_wire.setStyleSheet("*{background:#00000000;}")
        self.but_return_bind_wire.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/retutn.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_return_bind_wire.setIcon(icon1)
        self.but_return_bind_wire.setIconSize(QtCore.QSize(30, 30))
        self.but_return_bind_wire.setObjectName("but_return_bind_wire")
        MainWindow.setCentralWidget(self.centralwidget)
        self.set_machine_user = QtWidgets.QAction(MainWindow)
        self.set_machine_user.setObjectName("set_machine_user")
        self.act_set_wire_malh = QtWidgets.QAction(MainWindow)
        self.act_set_wire_malh.setObjectName("act_set_wire_malh")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_2.pressed.connect(MainWindow.Set_Table)
        self.tab_thing_all.cellDoubleClicked['int','int'].connect(MainWindow.TEST)
        self.but_return_bind_wire.clicked.connect(MainWindow.return_mainwindow)
        self.tabWidget.currentChanged['int'].connect(MainWindow.get_tabwidget_int)
        self.pushButton.clicked.connect(MainWindow.confire_reslute)
        self.pushButton_3.clicked.connect(MainWindow.Clean_All)
        self.lin_worker_id.returnPressed.connect(MainWindow.Seek_wireinfo)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "物品位置數量盤點"))
        self.label.setText(_translate("MainWindow", "厂牌ID"))
        self.com_desc.setItemText(0, _translate("MainWindow", "修改"))
        self.com_desc.setItemText(1, _translate("MainWindow", "删除"))
        self.com_desc.setItemText(2, _translate("MainWindow", "增加"))
        self.label_2.setText(_translate("MainWindow", "工号"))
        self.label_9.setText(_translate("MainWindow", "邮箱"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
        self.label_10.setText(_translate("MainWindow", "部门代码"))
        self.label_8.setText(_translate("MainWindow", "手机号码"))
        self.pushButton_3.setText(_translate("MainWindow", "清除"))
        self.label_7.setText(_translate("MainWindow", "部门名称"))
        self.label_5.setText(_translate("MainWindow", "姓名"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "增删改查"))
        self.pushButton_4.setText(_translate("MainWindow", "未开发"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "盘点"))
        self.lab_lh_address.setText(_translate("MainWindow", "0"))
        self.pushButton_2.setText(_translate("MainWindow", "刷新"))
        item = self.tab_thing_all.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "工号"))
        item = self.tab_thing_all.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tab_thing_all.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "厂牌ID"))
        item = self.tab_thing_all.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "手机号码"))
        item = self.tab_thing_all.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "部门名称"))
        item = self.tab_thing_all.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "部门代码"))
        item = self.tab_thing_all.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "邮箱"))
        item = self.tab_thing_all.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "时间"))
        self.set_machine_user.setText(_translate("MainWindow", "设定机种"))
        self.act_set_wire_malh.setText(_translate("MainWindow", "设定线材料号"))

import wire_images_rc
