import os

os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\wire_ui.py C:\Users\Administrator\Desktop\today_thing_register\UI\wire_ui.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\Thing_Check.py C:\Users\Administrator\Desktop\today_thing_register\UI\Thing_Check.ui')
os.system(r'pyrcc5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\wire_images_rc.py C:\Users\Administrator\Desktop\today_thing_register\UI\wire_images.qrc')
os.system(r'pyrcc5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\IMAGES_QRC_rc.py C:\Users\Administrator\Desktop\today_thing_register\UI\IMAGES_QRC.qrc')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\history.py C:\Users\Administrator\Desktop\today_thing_register\UI\history.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\Bind_wire.py C:\Users\Administrator\Desktop\today_thing_register\UI\Bind_wire.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\wireandmachine_lh.py C:\Users\Administrator\Desktop\today_thing_register\UI\wireandmachine_lh.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\Date_Analyse.py C:\Users\Administrator\Desktop\today_thing_register\UI\Date_Analyse.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\time_seek.py C:\Users\Administrator\Desktop\today_thing_register\UI\time_seek.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\SERSON.py C:\Users\Administrator\Desktop\today_thing_register\UI\SERSON.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\Set_Machine.py C:\Users\Administrator\Desktop\today_thing_register\UI\Set_Machine.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\set_machine_kitting.py C:\Users\Administrator\Desktop\today_thing_register\UI\Set_Machine_kitting.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\Main_Window.py C:\Users\Administrator\Desktop\today_thing_register\UI\MainWindow.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\lend_registe.py C:\Users\Administrator\Desktop\today_thing_register\UI\lend_registe.ui')
# os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\center_test.py C:\Users\Administrator\Desktop\today_thing_register\UI\center_test.ui')
# os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\Update.py C:\Users\Administrator\Desktop\today_thing_register\UI\Update.ui')
# os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\install.py C:\Users\Administrator\Desktop\today_thing_register\UI\install.ui')
# os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\Admin_Resigner.py C:\Users\Administrator\Desktop\today_thing_register\UI\Admin_Resigner.ui')
# os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\Login.py C:\Users\Administrator\Desktop\today_thing_register\UI\LOGIN.ui')
# os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\put_in.py C:\Users\Administrator\Desktop\today_thing_register\UI\put_in.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\write_password.py C:\Users\Administrator\Desktop\today_thing_register\UI\write_password.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\gif.py C:\Users\Administrator\Desktop\today_thing_register\UI\gif.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\sound.py C:\Users\Administrator\Desktop\today_thing_register\UI\sound.ui')
# os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\barcode.py C:\Users\Administrator\Desktop\today_thing_register\UI\barcode.ui')
# os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\thing_keep_hint.py C:\Users\Administrator\Desktop\today_thing_register\UI\thing_keep_hint.ui')
# os.system(r'pyrcc5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\IMAGES_QRC_rc.py C:\Users\Administrator\Desktop\today_thing_register\UI\IMAGES_QRC.qrc')

os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\set_address_red.py C:\Users\Administrator\Desktop\today_thing_register\UI\set_address_red.ui')
os.system(r'pyuic5 -o C:\Users\Administrator\Desktop\today_thing_register\UI\set_shortcut.py C:\Users\Administrator\Desktop\today_thing_register\UI\set_shortcut.ui')
#一个改名字的的方法,得到在某地的文件的大小
# os.rename("D:\\hblcmftp\\FD-flicker\\Main_Window_Show.down" ,"D:\\hblcmftp\\FD-flicker\\Main_Window_Show.exe")
# while True:
#     time.sleep(0.1)
#     a=os.path.getsize("D:\\hblcmftp\\FD-flicker\\Main_Window_Show.down")
#     print(a)