# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\20190822\Date_Analyse.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1286, 761)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/10.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.com_lines = QtWidgets.QComboBox(self.centralwidget)
        self.com_lines.setGeometry(QtCore.QRect(280, 230, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.com_lines.setFont(font)
        self.com_lines.setObjectName("com_lines")
        self.com_lines.addItem("")
        self.com_lines.setItemText(0, "")
        self.com_lines.addItem("")
        self.com_lines.addItem("")
        self.com_lines.addItem("")
        self.com_lines.addItem("")
        self.com_lines.addItem("")
        self.com_lines.addItem("")
        self.com_lines.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 360, 31, 20))
        self.label_3.setObjectName("label_3")
        self.com_lines_son = QtWidgets.QComboBox(self.centralwidget)
        self.com_lines_son.setGeometry(QtCore.QRect(280, 300, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.com_lines_son.setFont(font)
        self.com_lines_son.setObjectName("com_lines_son")
        self.com_lines_son.addItem("")
        self.com_lines_son.setItemText(0, "")
        self.com_thing_class = QtWidgets.QComboBox(self.centralwidget)
        self.com_thing_class.setGeometry(QtCore.QRect(790, 230, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.com_thing_class.setFont(font)
        self.com_thing_class.setObjectName("com_thing_class")
        self.com_thing_class.addItem("")
        self.com_thing_class.setItemText(0, "")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.com_thing_class_son = QtWidgets.QComboBox(self.centralwidget)
        self.com_thing_class_son.setGeometry(QtCore.QRect(790, 300, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.com_thing_class_son.setFont(font)
        self.com_thing_class_son.setMaxVisibleItems(20)
        self.com_thing_class_son.setObjectName("com_thing_class_son")
        self.com_thing_class_son.addItem("")
        self.com_thing_class_son.setItemText(0, "")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(850, 360, 61, 21))
        self.label_4.setObjectName("label_4")
        self.but_seek = QtWidgets.QPushButton(self.centralwidget)
        self.but_seek.setGeometry(QtCore.QRect(680, 490, 75, 51))
        self.but_seek.setObjectName("but_seek")
        self.but_close = QtWidgets.QPushButton(self.centralwidget)
        self.but_close.setGeometry(QtCore.QRect(510, 490, 75, 51))
        self.but_close.setObjectName("but_close")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(670, 140, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(510, 140, 61, 21))
        self.label.setObjectName("label")
        self.dat_finally = QtWidgets.QDateEdit(self.centralwidget)
        self.dat_finally.setGeometry(QtCore.QRect(650, 30, 121, 41))
        self.dat_finally.setObjectName("dat_finally")
        self.dat_start = QtWidgets.QDateEdit(self.centralwidget)
        self.dat_start.setGeometry(QtCore.QRect(469, 31, 131, 41))
        self.dat_start.setObjectName("dat_start")
        self.tim_finally = QtWidgets.QTimeEdit(self.centralwidget)
        self.tim_finally.setGeometry(QtCore.QRect(650, 90, 121, 41))
        self.tim_finally.setObjectName("tim_finally")
        self.tim_start = QtWidgets.QTimeEdit(self.centralwidget)
        self.tim_start.setGeometry(QtCore.QRect(470, 90, 131, 41))
        self.tim_start.setObjectName("tim_start")
        self.but_return = QtWidgets.QPushButton(self.centralwidget)
        self.but_return.setGeometry(QtCore.QRect(0, 0, 51, 41))
        self.but_return.setStyleSheet("*{BACKGROUND:#00000000;}")
        self.but_return.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/retutn.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_return.setIcon(icon1)
        self.but_return.setIconSize(QtCore.QSize(30, 30))
        self.but_return.setObjectName("but_return")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1286, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.act_shuhu = QtWidgets.QAction(MainWindow)
        self.act_shuhu.setObjectName("act_shuhu")
        self.act_future = QtWidgets.QAction(MainWindow)
        self.act_future.setObjectName("act_future")
        self.menu.addAction(self.act_shuhu)
        self.menu.addAction(self.act_future)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.but_close.pressed.connect(MainWindow.Matplotlib_New)
        self.but_seek.pressed.connect(MainWindow.Close_plot)
        self.but_return.clicked.connect(MainWindow.return_mainwindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "物品耗損查詢"))
        self.com_lines.setItemText(1, _translate("MainWindow", "FT"))
        self.com_lines.setItemText(2, _translate("MainWindow", "SKD"))
        self.com_lines.setItemText(3, _translate("MainWindow", "BMA"))
        self.com_lines.setItemText(4, _translate("MainWindow", "JI"))
        self.com_lines.setItemText(5, _translate("MainWindow", "IAS"))
        self.com_lines.setItemText(6, _translate("MainWindow", "AGIS"))
        self.com_lines.setItemText(7, _translate("MainWindow", "SET"))
        self.label_3.setText(_translate("MainWindow", "线体"))
        self.com_thing_class.setItemText(1, _translate("MainWindow", "電源線"))
        self.com_thing_class.setItemText(2, _translate("MainWindow", "測試線"))
        self.com_thing_class.setItemText(3, _translate("MainWindow", "驅動板"))
        self.com_thing_class.setItemText(4, _translate("MainWindow", "FFC"))
        self.label_4.setText(_translate("MainWindow", "物体种类"))
        self.but_seek.setText(_translate("MainWindow", "关闭"))
        self.but_close.setText(_translate("MainWindow", "查找"))
        self.label_2.setText(_translate("MainWindow", "结束时间"))
        self.label.setText(_translate("MainWindow", "起始时间"))
        self.dat_finally.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.dat_start.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.tim_finally.setDisplayFormat(_translate("MainWindow", "H:mm:ss"))
        self.tim_start.setDisplayFormat(_translate("MainWindow", "H:mm:ss"))
        self.menu.setTitle(_translate("MainWindow", "功能"))
        self.act_shuhu.setText(_translate("MainWindow", "耗损查询"))
        self.act_future.setText(_translate("MainWindow", "Future"))

import wire_images_rc
