# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\20190822\history.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1286, 761)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/19.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(670, 159, 61, 26))
        self.label_2.setObjectName("label_2")
        self.tim_start = QtWidgets.QTimeEdit(self.centralwidget)
        self.tim_start.setGeometry(QtCore.QRect(470, 129, 131, 31))
        self.tim_start.setObjectName("tim_start")
        self.but_clear = QtWidgets.QPushButton(self.centralwidget)
        self.but_clear.setGeometry(QtCore.QRect(670, 190, 71, 31))
        self.but_clear.setObjectName("but_clear")
        self.but_return = QtWidgets.QPushButton(self.centralwidget)
        self.but_return.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.but_return.setStyleSheet("*{background:#00000000;}")
        self.but_return.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/retutn.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_return.setIcon(icon1)
        self.but_return.setIconSize(QtCore.QSize(30, 30))
        self.but_return.setObjectName("but_return")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 190, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.dat_finally = QtWidgets.QDateEdit(self.centralwidget)
        self.dat_finally.setGeometry(QtCore.QRect(650, 90, 121, 31))
        self.dat_finally.setObjectName("dat_finally")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 230, 1221, 471))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(15)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        self.History_chioce = QtWidgets.QComboBox(self.centralwidget)
        self.History_chioce.setGeometry(QtCore.QRect(250, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.History_chioce.setFont(font)
        self.History_chioce.setObjectName("History_chioce")
        self.History_chioce.addItem("")
        self.History_chioce.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 159, 61, 21))
        self.label.setObjectName("label")
        self.tim_finally = QtWidgets.QTimeEdit(self.centralwidget)
        self.tim_finally.setGeometry(QtCore.QRect(650, 129, 121, 31))
        self.tim_finally.setObjectName("tim_finally")
        self.com_class = QtWidgets.QComboBox(self.centralwidget)
        self.com_class.setGeometry(QtCore.QRect(440, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.com_class.setFont(font)
        self.com_class.setToolTip("")
        self.com_class.setWhatsThis("")
        self.com_class.setObjectName("com_class")
        self.com_class.addItem("")
        self.com_class.setItemText(0, "")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.com_class.addItem("")
        self.dat_start = QtWidgets.QDateEdit(self.centralwidget)
        self.dat_start.setGeometry(QtCore.QRect(470, 90, 131, 31))
        self.dat_start.setObjectName("dat_start")
        self.com_lines = QtWidgets.QComboBox(self.centralwidget)
        self.com_lines.setGeometry(QtCore.QRect(670, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.com_lines.setFont(font)
        self.com_lines.setEditable(False)
        self.com_lines.setMaxVisibleItems(25)
        self.com_lines.setObjectName("com_lines")
        self.com_lines.addItem("")
        self.com_lines.setItemText(0, "")
        self.com_lines.addItem("")
        self.com_lines.addItem("")
        self.com_thing_class = QtWidgets.QComboBox(self.centralwidget)
        self.com_thing_class.setGeometry(QtCore.QRect(870, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.com_thing_class.setFont(font)
        self.com_thing_class.setEditable(False)
        self.com_thing_class.setMaxVisibleItems(25)
        self.com_thing_class.setObjectName("com_thing_class")
        self.com_thing_class.addItem("")
        self.com_thing_class.setItemText(0, "")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.com_thing_class.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 50, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(720, 50, 61, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(910, 50, 61, 21))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1286, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_to_lend = QtWidgets.QAction(MainWindow)
        self.action_to_lend.setObjectName("action_to_lend")
        self.action_lend = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/lend.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_lend.setIcon(icon2)
        self.action_lend.setObjectName("action_lend")
        self.menu.addAction(self.action_lend)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.seek)
        self.but_return.clicked.connect(MainWindow.return_mainwindow)
        self.but_clear.clicked.connect(MainWindow.clear)
        self.com_lines.activated['int'].connect(MainWindow.Get_Line_Index)
        self.com_class.activated['int'].connect(MainWindow.Get_Line_Index)
        self.com_thing_class.currentIndexChanged['int'].connect(MainWindow.Get_Line_Index)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "历史记录查询"))
        self.label_2.setText(_translate("MainWindow", "结束时间"))
        self.tim_start.setDisplayFormat(_translate("MainWindow", "H:mm:ss"))
        self.but_clear.setText(_translate("MainWindow", "清空"))
        self.pushButton.setText(_translate("MainWindow", "查找"))
        self.dat_finally.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "条形码"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "物品全称"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "操作时间"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ok编码"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ng编码"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "备注"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "数量"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "出入库类型"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "出入库方式"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "更换人"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "联系方式"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "领用课别"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "所用站点"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "ENG人员"))
        self.History_chioce.setItemText(0, _translate("MainWindow", "旧记录"))
        self.History_chioce.setItemText(1, _translate("MainWindow", "新记录"))
        self.label.setText(_translate("MainWindow", "起始时间"))
        self.tim_finally.setDisplayFormat(_translate("MainWindow", "H:mm:ss"))
        self.com_class.setItemText(1, _translate("MainWindow", "全选"))
        self.com_class.setItemText(2, _translate("MainWindow", "清除"))
        self.com_class.setItemText(3, _translate("MainWindow", "NG品更換"))
        self.com_class.setItemText(4, _translate("MainWindow", "OK退料"))
        self.com_class.setItemText(5, _translate("MainWindow", "NG退料"))
        self.com_class.setItemText(6, _translate("MainWindow", "新品入庫"))
        self.com_class.setItemText(7, _translate("MainWindow", "維修入庫（OK）"))
        self.com_class.setItemText(8, _translate("MainWindow", "加量需求"))
        self.com_class.setItemText(9, _translate("MainWindow", "外部借出"))
        self.com_class.setItemText(10, _translate("MainWindow", "NG出庫"))
        self.com_class.setItemText(11, _translate("MainWindow", "報廢出庫"))
        self.com_class.setItemText(12, _translate("MainWindow", "借用记录"))
        self.com_class.setItemText(13, _translate("MainWindow", "盤點記錄"))
        self.dat_start.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.com_lines.setItemText(1, _translate("MainWindow", "全选"))
        self.com_lines.setItemText(2, _translate("MainWindow", "清除"))
        self.com_thing_class.setItemText(1, _translate("MainWindow", "全选"))
        self.com_thing_class.setItemText(2, _translate("MainWindow", "清除"))
        self.com_thing_class.setItemText(3, _translate("MainWindow", "測試線"))
        self.com_thing_class.setItemText(4, _translate("MainWindow", "電源線"))
        self.com_thing_class.setItemText(5, _translate("MainWindow", "驅動板"))
        self.com_thing_class.setItemText(6, _translate("MainWindow", "FFC"))
        self.com_thing_class.setItemText(7, _translate("MainWindow", "Sensor"))
        self.com_thing_class.setItemText(8, _translate("MainWindow", "INV_電源線"))
        self.com_thing_class.setItemText(9, _translate("MainWindow", "其他"))
        self.label_3.setText(_translate("MainWindow", "操作类型"))
        self.label_4.setText(_translate("MainWindow", "线体"))
        self.label_5.setText(_translate("MainWindow", "物品种类"))
        self.menu.setTitle(_translate("MainWindow", "項目"))
        self.action_to_lend.setText(_translate("MainWindow", "導入數據"))
        self.action_lend.setText(_translate("MainWindow", "導出數據"))

import wire_images_rc
