# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\20190822\thing_keep_hint.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1286, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(11, 11, 1244, 698))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.tableWidget = QtWidgets.QTableWidget(self.page)
        self.tableWidget.setGeometry(QtCore.QRect(230, 10, 981, 681))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.com_choice = QtWidgets.QComboBox(self.page)
        self.com_choice.setGeometry(QtCore.QRect(60, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.com_choice.setFont(font)
        self.com_choice.setObjectName("com_choice")
        self.com_choice.addItem("")
        self.com_choice.addItem("")
        self.com_choice.addItem("")
        self.lin_thing_name = QtWidgets.QLineEdit(self.page)
        self.lin_thing_name.setGeometry(QtCore.QRect(12, 180, 181, 41))
        self.lin_thing_name.setObjectName("lin_thing_name")
        self.lin_hint_time = QtWidgets.QLineEdit(self.page)
        self.lin_hint_time.setGeometry(QtCore.QRect(12, 280, 181, 41))
        self.lin_hint_time.setObjectName("lin_hint_time")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(70, 220, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(70, 460, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(70, 320, 61, 16))
        self.label_3.setObjectName("label_3")
        self.but_confir = QtWidgets.QPushButton(self.page)
        self.but_confir.setGeometry(QtCore.QRect(20, 530, 61, 51))
        self.but_confir.setObjectName("but_confir")
        self.but_clear = QtWidgets.QPushButton(self.page)
        self.but_clear.setGeometry(QtCore.QRect(140, 530, 61, 51))
        self.but_clear.setObjectName("but_clear")
        self.dat_hint_time = QtWidgets.QDateTimeEdit(self.page)
        self.dat_hint_time.setGeometry(QtCore.QRect(10, 370, 181, 41))
        self.dat_hint_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 10, 1), QtCore.QTime(0, 0, 0)))
        self.dat_hint_time.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 8, 1), QtCore.QTime(0, 0, 0)))
        self.dat_hint_time.setMinimumDate(QtCore.QDate(2019, 8, 1))
        self.dat_hint_time.setCalendarPopup(True)
        self.dat_hint_time.setObjectName("dat_hint_time")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(90, 640, 31, 28))
        self.pushButton.setObjectName("pushButton")
        self.lin_thing_txm = QtWidgets.QLineEdit(self.page)
        self.lin_thing_txm.setGeometry(QtCore.QRect(12, 80, 181, 41))
        self.lin_thing_txm.setObjectName("lin_thing_txm")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(70, 130, 72, 15))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(420, 30, 381, 551))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1286, 21))
        self.menubar.setObjectName("menubar")
        self.menusetting = QtWidgets.QMenu(self.menubar)
        self.menusetting.setObjectName("menusetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiontime = QtWidgets.QAction(MainWindow)
        self.actiontime.setObjectName("actiontime")
        self.menusetting.addSeparator()
        self.menusetting.addAction(self.actiontime)
        self.menusetting.addSeparator()
        self.menubar.addAction(self.menusetting.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.but_confir.clicked.connect(MainWindow.confir_result)
        self.lin_hint_time.returnPressed.connect(MainWindow.set_hint_time)
        self.pushButton.clicked.connect(MainWindow.test)
        self.tableWidget.cellDoubleClicked['int','int'].connect(MainWindow.get_table_data)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "物品编码"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "物品名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "维护时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "到期时间"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "剩余时间"))
        self.com_choice.setItemText(0, _translate("MainWindow", "增加"))
        self.com_choice.setItemText(1, _translate("MainWindow", "修改"))
        self.com_choice.setItemText(2, _translate("MainWindow", "删除"))
        self.label.setText(_translate("MainWindow", "物品名称 "))
        self.label_2.setText(_translate("MainWindow", "到期时间"))
        self.label_3.setText(_translate("MainWindow", "使用时间"))
        self.but_confir.setText(_translate("MainWindow", "确认"))
        self.but_clear.setText(_translate("MainWindow", "清除"))
        self.dat_hint_time.setToolTip(_translate("MainWindow", "默认5个小时后,可修改"))
        self.dat_hint_time.setDisplayFormat(_translate("MainWindow", "yyyy-M-d hh:mm:ss"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_4.setText(_translate("MainWindow", "物品编码"))
        self.menusetting.setTitle(_translate("MainWindow", "setting"))
        self.actiontime.setText(_translate("MainWindow", "time"))

