# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\today_thing_register\UI\SERSON.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1286, 761)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/main.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 571, 651))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(25)
        self.tableWidget.verticalHeader().setDefaultSectionSize(37)
        self.tableWidget.verticalHeader().setMinimumSectionSize(10)
        self.com_Choice = QtWidgets.QComboBox(self.centralwidget)
        self.com_Choice.setGeometry(QtCore.QRect(280, 10, 119, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.com_Choice.setFont(font)
        self.com_Choice.setStyleSheet("QComboBox::drop-down {/*右侧按钮*/\n"
"    width: 20px;/*宽度*/\n"
"    background:  rgb(255, 255, 255,30);/*背景颜色*/\n"
"    \n"
"\n"
"\n"
"}")
        self.com_Choice.setMaxVisibleItems(20)
        self.com_Choice.setObjectName("com_Choice")
        self.com_Choice.addItem("")
        self.com_Choice.addItem("")
        self.com_Choice.addItem("")
        self.com_Choice.addItem("")
        self.com_chioce_comp_or_ser = QtWidgets.QComboBox(self.centralwidget)
        self.com_chioce_comp_or_ser.setGeometry(QtCore.QRect(140, 10, 119, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.com_chioce_comp_or_ser.setFont(font)
        self.com_chioce_comp_or_ser.setStyleSheet("")
        self.com_chioce_comp_or_ser.setMaxVisibleItems(20)
        self.com_chioce_comp_or_ser.setObjectName("com_chioce_comp_or_ser")
        self.com_chioce_comp_or_ser.addItem("")
        self.com_chioce_comp_or_ser.addItem("")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(610, 60, 651, 651))
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"        border: none;\n"
"        border-top-left-radius: 4px;\n"
"        border-top-right-radius: 4px;\n"
"        color: rgb(175, 175, 175);\n"
"        height: 325px;\n"
"        min-width: 85px;\n"
"        margin-right: 5px;\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(120, 90, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(110, 180, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(400, 90, 61, 20))
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 420, 93, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.com_Address = QtWidgets.QComboBox(self.tab)
        self.com_Address.setGeometry(QtCore.QRect(331, 130, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.com_Address.setFont(font)
        self.com_Address.setEditable(True)
        self.com_Address.setObjectName("com_Address")
        self.com_Station = QtWidgets.QComboBox(self.tab)
        self.com_Station.setGeometry(QtCore.QRect(50, 130, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.com_Station.setFont(font)
        self.com_Station.setEditable(True)
        self.com_Station.setObjectName("com_Station")
        self.com_Station.addItem("")
        self.com_Station.setItemText(0, "")
        self.com_Station.addItem("")
        self.com_Station.addItem("")
        self.lin_Worker = QtWidgets.QLineEdit(self.tab)
        self.lin_Worker.setGeometry(QtCore.QRect(50, 220, 181, 41))
        self.lin_Worker.setObjectName("lin_Worker")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(180, 420, 93, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(110, 270, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(410, 180, 41, 20))
        self.label_4.setObjectName("label_4")
        self.com_thing_status_info = QtWidgets.QComboBox(self.tab)
        self.com_thing_status_info.setGeometry(QtCore.QRect(330, 40, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.com_thing_status_info.setFont(font)
        self.com_thing_status_info.setEditable(True)
        self.com_thing_status_info.setObjectName("com_thing_status_info")
        self.com_thing_status_info.addItem("")
        self.com_thing_status_info.addItem("")
        self.com_thing_status_info.addItem("")
        self.com_thing_status_info.addItem("")
        self.com_thing_status_info.addItem("")
        self.lin_Num = QtWidgets.QLineEdit(self.tab)
        self.lin_Num.setGeometry(QtCore.QRect(52, 40, 181, 41))
        self.lin_Num.setObjectName("lin_Num")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(410, 270, 61, 20))
        self.label_6.setObjectName("label_6")
        self.dat_hint_time = QtWidgets.QDateTimeEdit(self.tab)
        self.dat_hint_time.setGeometry(QtCore.QRect(333, 220, 191, 41))
        self.dat_hint_time.setTabletTracking(False)
        self.dat_hint_time.setAcceptDrops(False)
        self.dat_hint_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dat_hint_time.setAutoFillBackground(False)
        self.dat_hint_time.setWrapping(False)
        self.dat_hint_time.setAccelerated(False)
        self.dat_hint_time.setKeyboardTracking(True)
        self.dat_hint_time.setCalendarPopup(True)
        self.dat_hint_time.setObjectName("dat_hint_time")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lin_delete = QtWidgets.QLineEdit(self.tab_2)
        self.lin_delete.setGeometry(QtCore.QRect(190, 100, 171, 31))
        self.lin_delete.setObjectName("lin_delete")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 150, 81, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 10, 61, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.but_return_bind_wire = QtWidgets.QPushButton(self.centralwidget)
        self.but_return_bind_wire.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.but_return_bind_wire.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.but_return_bind_wire.setStyleSheet("*{background:#00000000;}")
        self.but_return_bind_wire.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/retutn.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_return_bind_wire.setIcon(icon1)
        self.but_return_bind_wire.setIconSize(QtCore.QSize(30, 30))
        self.but_return_bind_wire.setObjectName("but_return_bind_wire")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1286, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_SERSON = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/count.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_SERSON.setIcon(icon2)
        self.action_SERSON.setObjectName("action_SERSON")
        self.action_to_lend = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_to_lend.setIcon(icon3)
        self.action_to_lend.setObjectName("action_to_lend")
        self.action_lend = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/lend.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_lend.setIcon(icon4)
        self.action_lend.setObjectName("action_lend")
        self.menu.addAction(self.action_SERSON)
        self.menu.addAction(self.action_to_lend)
        self.menu.addAction(self.action_lend)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tableWidget.cellDoubleClicked['int','int'].connect(MainWindow.TEST)
        self.pushButton_4.clicked.connect(MainWindow.Clean_All)
        self.pushButton_3.clicked.connect(MainWindow.delete)
        self.pushButton.clicked.connect(MainWindow.confire_reslute)
        self.pushButton_2.clicked.connect(MainWindow.Clean_All)
        self.but_return_bind_wire.clicked.connect(MainWindow.return_mainwindow)
        self.lin_Num.returnPressed.connect(MainWindow.thing_showinfo)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SERSON_WINDOWS"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "物品编码"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "保存情况"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "物品状态"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "操作人员"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "物品位置"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "维护时间"))
        self.com_Choice.setItemText(0, _translate("MainWindow", "所有"))
        self.com_Choice.setItemText(1, _translate("MainWindow", "OK"))
        self.com_Choice.setItemText(2, _translate("MainWindow", "NG"))
        self.com_Choice.setItemText(3, _translate("MainWindow", "BF"))
        self.com_chioce_comp_or_ser.setItemText(0, _translate("MainWindow", "SERSON"))
        self.com_chioce_comp_or_ser.setItemText(1, _translate("MainWindow", "电脑"))
        self.label.setText(_translate("MainWindow", "编号"))
        self.label_2.setText(_translate("MainWindow", "物品状态"))
        self.label_5.setText(_translate("MainWindow", "保存情况"))
        self.pushButton_2.setText(_translate("MainWindow", "清除"))
        self.com_Station.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">物品是好还是坏</span></p></body></html>"))
        self.com_Station.setItemText(1, _translate("MainWindow", "OK"))
        self.com_Station.setItemText(2, _translate("MainWindow", "NG"))
        self.lin_Worker.setText(_translate("MainWindow", "黃林燦"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
        self.label_3.setText(_translate("MainWindow", "操作人员"))
        self.label_4.setText(_translate("MainWindow", "位置"))
        self.com_thing_status_info.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">物品是完好，还是某零件损坏，还是其他</span></p><p><br/></p></body></html>"))
        self.com_thing_status_info.setItemText(0, _translate("MainWindow", "SERSON"))
        self.com_thing_status_info.setItemText(1, _translate("MainWindow", "电脑"))
        self.com_thing_status_info.setItemText(2, _translate("MainWindow", "完好"))
        self.com_thing_status_info.setItemText(3, _translate("MainWindow", "損壞"))
        self.com_thing_status_info.setItemText(4, _translate("MainWindow", "其他原因"))
        self.label_6.setText(_translate("MainWindow", "维护时间"))
        self.dat_hint_time.setDisplayFormat(_translate("MainWindow", "yyyy-M-d hh:mm:ss"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "电脑,SERSON操作"))
        self.pushButton_3.setText(_translate("MainWindow", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "删除"))
        self.pushButton_4.setText(_translate("MainWindow", "查找"))
        self.menu.setTitle(_translate("MainWindow", "项目"))
        self.action_SERSON.setText(_translate("MainWindow", "serson重新统计"))
        self.action_to_lend.setText(_translate("MainWindow", "導入數據"))
        self.action_lend.setText(_translate("MainWindow", "導出數據"))

import wire_images_rc
